global:
  scrape_interval: 1s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: postgres-prometheus-exporter
    static_configs:
      - targets: ["postgres-prometheus-exporter:9187"]

  - job_name: nginx-prometheus-exporter
    static_configs:
      - targets: ["nginx-prometheus-exporter:9113"]
