global:
  scrape_interval: 1s

scrape_configs:
  - job_name: engs-tcc-prometheus
    static_configs:
      - targets: ["localhost:9090"]
  
  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]
  
  - job_name: engs-tcc-db-prometheus-exporter
    static_configs:
      - targets: ["engs-tcc-db-prometheus-exporter:9187"]
